# Generated by Django 5.0.6 on 2024-06-22 13:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdf_type',
            name='object',
        ),
        migrations.AddField(
            model_name='rdf_type',
            name='object_ont',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_ont', to='ontology_auth.object'),
        ),
        migrations.AddField(
            model_name='rdf_type',
            name='ontology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ontology', to='ontology_auth.object'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rdf_type',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rdf_type',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='ontology_auth.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('access', models.CharField(choices=[('Global', 'Общедоступная'), ('Private', 'Приватная')], default='Global', max_length=50)),
                ('craeted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ontology', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
