# Generated by Django 5.0.6 on 2024-06-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontology_auth', '0002_remove_rdf_type_object_rdf_type_object_ont_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ontology',
            old_name='craeted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='rdf_type',
            name='object_ont',
        ),
        migrations.RemoveField(
            model_name='rdf_type',
            name='ontology',
        ),
        migrations.RemoveField(
            model_name='rdf_type',
            name='subject',
        ),
    ]
