# Generated by Django 5.0.6 on 2024-06-22 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontology_auth', '0003_rename_craeted_at_ontology_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdf_type',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ontology', to='ontology_auth.object'),
        ),
        migrations.AddField(
            model_name='rdf_type',
            name='ontology',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ontology', to='ontology_auth.ontology'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rdf_type',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ontology', to='ontology_auth.subject'),
        ),
    ]
